import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/Navigation/Navigation";

const AlexandriaFont = Alexandria({
  subsets: ["latin"],
  variable: "--font-alexandria",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${AlexandriaFont.variable} antialiased relative`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
